<p>&nbsp;</p>
# __Ti-84 Graphing Calculator Programming__
<p>The Ti-84 graphing calculators have the ability to create your own programs
to show the sequences and radians, compute the quadratic formula, and more!</p>
<p>In tenth grade, I grew tired of having to memorize math formulas, so in my calculator 
I first started out with having them displayed when running a created program. 
This obviously gave me an upper hand on tests and the math teacher approved of 
this as it was impressive to use a calculator with this type of reasoning.</p>
<p>Becoming more interested in coding on calculators I began programming tiny programs 
turning what was only being displayed into real-time calculations. 
The programming language is called, _TI-Basics_</p>
<p>I have not resorted to using my programs anymore, but calculator programs were 
legal on the ACT exams! The only rule that applied was the programs could only have 
10 lines of code, however it need said how many programs you could have...</p>
### Attached below is the complete source code for my program: ALGEBRA2
```text
ClrHome
Lbl 0
Menu("Algebra 2 Home","Coordinate Geometry",A1,"Trigonometry",A2,"Sequences & Series",A3,"Degrees & Radians",A4,"Quadratic Formula",A5,"Forms",A6,"End",A7)

ClrHome

Lbl A1
Menu("COORDINATE GEOMETRY","DISTANCE",B1,"MIDPOINT",B2,"SLOPE",B3,"",0)
ClrHome
Lbl B1
Disp "d=√(X2-X1)+(Y2-Y1)
Input "X1? ",A
Input "Y1? ",B 
Input "X2? ",C
Input "Y2? ",D
(C-A)→J
(D-B)→K
√(J+K)→Z
Disp Z
Pause 
Goto A1
Lbl B2
ClrHome
Disp "((X1+X2)/2,(Y1+Y2)/2)"
Input "X1? ",A
Input "Y1? ",B
Input "X2? ",C
Input "Y2? ",D
(A+C)/2→X
(B+D)/2→Y
Disp X,Y
Pause 
Goto A1
Lbl B3
ClrHome
Disp "m=(Y1-Y2)/(X1-X2)"
Input "X1? ",A
Input "Y1? ",B
Input "X2? ",C
Input "Y2? ",D
(D-B)→E
(C-A)→F
(E/F)→G
Disp "SLOPE=",G
Pause 
Goto A1


Lbl A2
Menu("Algebraic Trig.","Law Of Consine",H1,"Law Of Sines",H2,"Six Value Trig.",H3,"Coterminal Angle",H4,"[black arrow left]",0)
Lbl H1
Menu("LAW OF COSINES","Little A",D1,"Little B",D2,"Little C",D3,"Finding Angles",D4,"[black arrow left]",A2)
Lbl D1
ClrHome
Disp "a^2=b^2+c^2-2(b)(c)cos(A°)"
Input "A°?",A
Input "b?",B
Input "c?",C
B^2+C^2-2(B)(C)cos(A°)→S
√(S→I
round(I,2)→X
Disp X
Pause 
Goto A2
Lbl D2
ClrHome
Disp "b^2=a^2+c^2-2(a)(c)cos(B°)"
Input "a?",A
Input "B°?",B
Input "c?",C
A^2+C^2-2(A)(C)cos(B°)→S
√(S→I
round(I,2)→X
Disp X
Pause 
Goto A2
Lbl D3
ClrHome
Disp "c^2=a^2+b^2-2(a)(b)cos(C°)"
Input "a?",A
Input "b?",B
Input "C°?",C
A^2+B^2-2(A)(B)cos(C°)→S
√(S→I
round(I,2)→X
Disp X
Pause 
Goto A2
Lbl D4
Menu("Find Angle A,B,C","A°",I1,"B°",I2,"C°",I3,"[black arrow left]",A2)
Lbl I1
ClrHome
Disp "Given three sides, find A°"
Input "a?",A
Input "b?",B
Input "c?",C
(B^2+C^2-A^2)/(2(B)(C))→K
cos^-1(K)→O
round(O,0)→Z
round(Z,0)→Y
Disp "Angle A",Y
Pause  
Goto D4 
Lbl I2
ClrHome
Disp "Given three sides, find B°"
Input "a?",A
Input "b?",B
Input "c?",C
(C^2+A^2-B^2)/(2(C)(A))→K
cos^-1(K)→O
round(O,0)→Z
round(Z,0)→Y
Disp "Angle B",Y
Pause  
Goto D4 
Lbl I3
ClrHome
Disp "Given three sides, find C°"
Input "a?",A
Input "b?",B
Input "c?",C
(A^2+B^2-C^2)/(2(A)(B))→K
cos^-1(K)→O
round(O,0)→Z
round(Z,0)→Y
Disp "Angle C",Y
Pause 
Goto D4 
Lbl H2
Menu("Area Of Triangles","SIN A",C1,"SIN B",C2,"SIN C",C3,"[black arrow left]",A2)
Lbl C1
ClrHome
Disp "1/2(B)(C)sin(A)"
Prompt A
Prompt B
Prompt C
1/2(B)(C)sin(A)→X
round(X,1)→Y
Disp Y
Stop
Lbl C2
Disp "1/2(A)(C)sin(B)"
Prompt A
Prompt B
Prompt C
1/2(A)(C)sin(B)→O
round(O,1)→P
Disp P
Stop
Lbl C3
ClrHome
Disp "1/2(A)(B)sin(C)"
Prompt A
Prompt B
Prompt C
1/2(A)(B)sin(C)→E
round(E,1)→F
Disp F
Stop
Lbl C4
Stop
Lbl H3
ClrHome
Disp "Opp,Hyp,Adj,OF θ"
Prompt O
Prompt H
Prompt A
Disp "Sin θ",O/H[black arrow right]Frac
Disp "[ENTER] FOR NEXT"
Pause 
Disp "Cos θ",A/H[black arrow right]Frac
Disp "[ENTER] FOR NEXT"
Pause 
Disp "Tan θ",O/A[black arrow right]Frac
Disp "[ENTER] FOR NEXT"
Pause 
Disp "Csc θ",H/O[black arrow right]Frac
Disp "[ENTER] FOR NEXT"
Pause 
Disp "Sec θ",H/A[black arrow right]Frac
Disp "[ENTER] FOR NEXT"
Pause 
Disp "Cot θ",A/O[black arrow right]Frac
Disp "[ENTER] TO END"
Pause 
Goto A2
Lbl H4
ClrHome
Menu("COTERMINAL ANGLE","Positive/Negative Angle",J1,"[black arrow left]",0)
Lbl J1
ClrHome
Disp "Degree°?"
Prompt D
Disp "Postive Angle",D°+360
Disp "Negative Angle",D°-360
Pause 
Goto A2



Lbl A3
ClrHome
Menu("Sequences and Series","Arithmetic Seq",E1,"Arithmetic Ser",E2,"Geometric Seq",E3,"Geometric Ser",E4,"[ black arrow left]",0)
Lbl E1
ClrHome
Disp "A1?"
Prompt A
Disp "D?"
Prompt D
Disp "N?"
Prompt N
(A+(N-1)D)→L
Disp L
Pause 
Goto A3
Lbl E2
ClrHome
Disp "A1?"
Prompt A
Disp "D?"
Prompt D
Disp "N?"
Prompt N
(N/2)→K
2(A)→J
(J+(N-1)(D))→L
(K)(L)→X
Disp X
Pause 
Goto A3
Lbl E3
ClrHome
Disp "A1?"
Prompt A
Disp "R?"
Prompt R
Disp "N-1?"
Prompt N
(A)(R)^(N-1)→L
Disp L
Pause 
Goto A3
Lbl E4
ClrHome
Disp "A1?"
Prompt A
Disp "N?"
Prompt N
Disp "R?"
Prompt R
(A-A(R)^N)→K
(1-R)→Q
(K/Q)→S
Disp S
Pause 
Goto A3


Lbl A4
Menu("DEGREES RADIANS","Degree to Radian",F1,"Radian to Degree",F2,"[black arrow left]",0)
Lbl F1
ClrHome
Input "?° ",D
D*(π/180)→X
Disp X
Pause 
Goto A4
Lbl F2
ClrHome
Input "Xπ? ",X
Input "Xπ/A? ",A
(X/A)*180→D
Disp D°
Pause  
Goto A4


Lbl A5
ClrHome
Menu("Quadratic Formula","–B+√(B-4AC)/2A",G1,"–B-√(B-4AC)/2A",G2,"BOTH",G3,"[black arrow left]",0)
ClrHome
Lbl G1
ClrHome
Disp "–B+√(B^2-4AC)/2A"
Disp "X^2=A,X=B,WHOLE NUMBER=C"
Input "A?",A
Input "B?",B
Input "C?",C
If (B^2-(4AC))<0
Then
Disp "No Solution"
Pause 
Goto A5
Else
If A=0
Then
Disp "Not Quadratic"
Pause 
Goto A5
Else
(–B+√(B^2-4AC))/(2A)→W
Disp W
Pause 
Goto A5
Lbl G2
ClrHome
Disp "–B-√(B^2-4AC)/2A"
Disp "X^2=A,X=B,WHOLE NUMBER=C
Input "A?",A
Input "B?",B
Input "C?",C
If (B^2-(4AC))<0
Then
Disp "No Solution"
Pause 
Goto A5
Else
If A=0
Then
Disp "Not Quadratic"
Pause 
Goto A5
Else
(–B-√(B^2-4AC))/(2A)→H
Disp H
Pause 
Goto A5
Lbl G3
ClrHome
Disp "X^2=A,X=B,WHOLE NUMBER=C"
Input "A?",A
Input "B?",B
Input "C?",C
If (B^2-(4AC))<0
Then
Disp "No Solution"
Pause 
Goto A5
Else
If A=0
Then
Disp "Not Quadratic"
Pause 
Goto A5
Else
Disp "[–B+√(B^2-4AC)/2A]
(–B+√(B^2-4AC))/(2A)→V
Disp V
Disp "[–B-√(B^2-4AC)/2A]"
(–B-√(B^2-4AC))/(2A)→Q
Disp Q
Pause 
Goto A5


Lbl A6
ClrHome
Menu("SAMPLE OF FORMS","SLOPE INTERCEPT FORM",Z1,"POINT SLOPE FORM",Z2,"STANDARD FORM",Z3,"[black arrow left]",0)
Lbl Z1
Disp "Y=MX+B"
Pause 
Disp "2X+Y=5","Y=–2X+5"
Pause 
Goto A6
Lbl Z2
Disp "Y-Y1=M(X-X1)"
Pause 
Disp "Y-2=2/3(X-0)","Y-2=2/3X"
Pause 
Goto A6
Lbl Z3
Disp "AX+BY=C"
Pause 
Disp "M=–A/B","X–INT=(C/A,0)","Y–INT=(0,C/B)"
Pause 
Disp "Y=2X-6","–2X+Y=–6","–2X+Y=–6","2X-Y=6"
Pause 
Goto A6

Lbl A7
Stop
```
